import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar"

import { SparklesCore } from "@/components/sparkles"
export const metadata: Metadata = {
  title: "Carlos Calderon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black/[0.98] antialiased bg-grid-white/[0.02] relative  ">
        <div className="relative z-10">
          <Navbar />
        </div>
        <div className="h-full w-full absolute inset-0 z-0">
          <SparklesCore
            id="tsparticlesfullpage"
            background="transparent"
            minSize={0.6}
            maxSize={1.4}
            particleDensity={100}
            className="w-full h-full"
            particleColor="#FFFFFF"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
