import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar"
//import SplashCursor from "@/components/Efecto";
export const metadata: Metadata = {
  title: "Carlos Calderon",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black/[0.98] antialiased bg-grid-white/[0.02] relative  ">
        <div className="relative">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
